/**
 * Raju Garu Hotel - Offline Point-of-Sale Register, KOT Dispatch & Shift Summary Domain Exports
 */

export * from './pos_register_1';
export * from './pos_register_2';
export * from './pos_register_3';
export * from './pos_register_4';
export * from './pos_register_5';
export * from './pos_register_6';
export * from './pos_register_7';
export * from './pos_register_8';
export * from './pos_register_9';
export * from './pos_register_10';
export * from './pos_register_11';
export * from './pos_register_12';
export * from './pos_register_13';
export * from './pos_register_14';
export * from './pos_register_15';
export * from './pos_register_16';
export * from './pos_register_17';
export * from './pos_register_18';
export * from './pos_register_19';
export * from './pos_register_20';
export * from './pos_register_21';
export * from './pos_register_22';
export * from './pos_register_23';
export * from './pos_register_24';
export * from './pos_register_25';
export * from './pos_register_26';
export * from './pos_register_27';
export * from './pos_register_28';
export * from './pos_register_29';
export * from './pos_register_30';
export * from './pos_register_31';
export * from './pos_register_32';
export * from './pos_register_33';
export * from './pos_register_34';
export * from './pos_register_35';
export * from './pos_register_36';
export * from './pos_register_37';
export * from './pos_register_38';
export * from './pos_register_39';
export * from './pos_register_40';
export * from './pos_register_41';
export * from './pos_register_42';
export * from './pos_register_43';
export * from './pos_register_44';
export * from './pos_register_45';
