/**
 * Raju Garu Hotel - Village Feast Catering Bookings, Earthen Stove Allocations & Mass Orders Domain Exports
 */

export * from './village_feast_1';
export * from './village_feast_2';
export * from './village_feast_3';
export * from './village_feast_4';
export * from './village_feast_5';
export * from './village_feast_6';
export * from './village_feast_7';
export * from './village_feast_8';
export * from './village_feast_9';
export * from './village_feast_10';
export * from './village_feast_11';
export * from './village_feast_12';
export * from './village_feast_13';
export * from './village_feast_14';
export * from './village_feast_15';
export * from './village_feast_16';
export * from './village_feast_17';
export * from './village_feast_18';
export * from './village_feast_19';
export * from './village_feast_20';
export * from './village_feast_21';
export * from './village_feast_22';
export * from './village_feast_23';
export * from './village_feast_24';
export * from './village_feast_25';
export * from './village_feast_26';
export * from './village_feast_27';
export * from './village_feast_28';
export * from './village_feast_29';
export * from './village_feast_30';
export * from './village_feast_31';
export * from './village_feast_32';
export * from './village_feast_33';
export * from './village_feast_34';
export * from './village_feast_35';
export * from './village_feast_36';
export * from './village_feast_37';
export * from './village_feast_38';
export * from './village_feast_39';
export * from './village_feast_40';
export * from './village_feast_41';
export * from './village_feast_42';
export * from './village_feast_43';
export * from './village_feast_44';
export * from './village_feast_45';
